config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :celestials
  resources :users, only: [:edit, :update, :show]
  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :avatar, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :celestials, through: :interests
  has_many :celestials, dependent: :destroy
  has_many :interests, dependent: :destroy
  has_many :messages
  has_many :conversations

  validates :first_name, presence: true, length: { maximum: 35 }
  validates :last_name, presence: true, length: { maximum: 35 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    redirect_to root_path
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  protected

  def after_sign_up_path_for(resource)
    user_path(current_user) # Or :prefix_to_your_route
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    authorize @user
    if @user.update(update_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = current_user
    authorize @user
    @user.destroy
    redirect_to root_path
  end

  private

  def update_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :bio)
  end

end

app/views/users/edit.html.erb
<h2>Edit My Profile <%= @user.first_name %></h2>

<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :first_name,
                autofocus: true ,
                input_html: { autocomplete: "name" }%>
    <%= f.input :last_name,
                autofocus: true ,
                input_html: { autocomplete: "last-name" }%>
    <%= f.input :email,
                autofocus: true ,
                input_html: { autocomplete: "email" }%>

    <%= f.input :avatar %>
    <%= f.input :avatar_cache, as: :hidden %>
    <%= f.input :bio %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Edit My Profile" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container" id="welcome">
  <div><h2>Welcome, <%= current_user.first_name %>!</h2></div>
</div>

<div class="tab-container">
  <div class="tab">
    <button id="profile-button" class="tablinks" onclick="openPage(event, 'Profile')"><h4><i class="fas fa-user-astronaut"></i>My Profile</h4></button>
    <button class="tablinks" onclick="openPage(event, 'Interests')"><h4><i class="fas fa-space-shuttle"></i>My Interests</h4></button>
    <button class="tablinks" onclick="openPage(event, 'Celestials')"><h4><i class="fas fa-sun"></i>My Celestials</h4></button>
  </div>

  <div id="Profile" class="tabcontent">
    <div class="tab-body">
       <div clas="content">
        <h2><%= current_user.first_name %> <%= current_user.last_name %>  <div><%= cl_image_tag current_user.avatar,
      transformation: [{ height: 100, width: 100, crop: :thumb, gravity: :face}], style: "border-radius:50%;"%></h2></div>
        <h3><%= current_user.bio %></h3>
       </div>
      <button class="button-main"><%= link_to "Edit My Profile", edit_user_path(current_user) %></button>
      <div id="delete"><%= link_to "Delete My Profile", user_registration_path(current_user), method: :delete, data: { confirm: "Are you sure about this? The celestial gods will be angry!"} %></div>
    </div>
  </div>

  <div id="Interests" class="tabcontent">
    <div class="tab-body">
      <div class="tab-card">
        <div class="content">
          <% 'current_user.celestials.interests.each do |interest|' %>
          <h3><%= 'interest.name' %></h3>
        </div>
        <button class="button-main">See Details</button>
      </div>
    </div>
  </div>

  <div id="Celestials" class="tabcontent">
    <div class="tab-body">
      <div class="tab-card">
        <div class="content">
          <% current_user.celestials.each do |celestial| %>
            <h3><strong><%= celestial.name %></strong> (category: <%= celestial.category %>)</h3>
            <p>€<%= celestial.price %></p>
        </div>
            <button class="button-main"><%= link_to "Delete Celestial", celestial_path(celestial), method: :delete, data: { confirm: "Are you sure?"} %></button>
          <% end %>
        </div>
      <button class="button-main"><%= link_to "Add a Celestial", new_celestial_path(current_user) %></button>
    </div>
  </div>

</div>


<script>

function openPage(evt, headingName) {

    // Declare all variables
    var i, tabcontent, tablinks;
    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the link that opened the tab
    document.getElementById(headingName).style.display = "block";
    event.currentTarget.className += " active";
}

document.getElementById('profile-button').focus();
openPage(event,'Profile');
</script>