config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :celestials
  resources :users, only: [:edit, :update, :show]
  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/views/shared/_card.html.erb
<a href='/celestials/<%= celestial.id %>' style="text-decoration: none;">
<div class="card" data-effect="zoom">
  <figure  class="card__image">
    <%= cl_image_tag celestial.photo, alt: celestial.name %>
  </figure>
  <div class="card__header">
    <figure class="card__profile">

    </figure>
  </div>
  <div class="card__body">
    <div class="black-bar">
      <h3 class="card__name"><%= celestial.name %></h3>
      <p class="card__price">€<%= celestial.price %></p>
    </div>
    <p class="card__bio"></p>
  </div>
  <div class="card__footer">
    <p class="card__category center-text" align="center"><%= celestial.category %></p>
  </div>
</div>
</a>

app/views/shared/_feature-card.html.erb
<div class="card feature" data-effect="zoom" data-card='<%= index %>'>
  <button class="card__save  js-save" type="button">
    <i class="fa  fa-bookmark"></i>
   </button>
  <figure  class="card__image">
    <%= cl_image_tag celestial.photo, alt: celestial.name, class: 'feature' %>
  </figure>
  <div class="card__header">
    <figure class="card__profile">

    </figure>
  </div>
  <div class="card__body">
    <h3 class="card__name"><%= celestial.name %></h3>
    <p class="card__job"><%= celestial.category %></p>
    <p class="card__bio"> A really, really cool celestial body.</p>
  </div>
  <div class="card__footer">
    <p class="card__date">Feb 10 2018</p>
    <p class=""></p>
  </div>
</div>

app/views/shared/_filters.html.erb
<!-- filters -->
<div class="filter-container">
  <button class='button-main <%= "active" if @categories %>' data-toggle="modal" data-target="#category">
    Category
  </button>
  <button class='button-main <%= "active" if @min_max %>' data-toggle="modal" data-target="#price">
    Price
  </button>
  <%= form_tag celestials_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    id: "search-bar",
    class: "form-control",
    placeholder: "Find your dream celestial..."
  %>
<% end %>
</div>


<!-- category modal -->
<div class='modal fade' id="category" role="dialog">
  <div class="modal-dialog">

    <!-- category content-->
    <div class="modal-content modal-padding modal-background">
      <p class="text-center">What kind of celestial are you interested in?</p>
      <%= form_tag({}, {method: :get, enforce_utf8: browser.ie?}) do %>
        <% Celestial::CATEGORIES.each do |category| %>
          <%= check_box_tag 'category[]', category, checked = @categories && @categories.include?(category)%>
          <%= category %>
          <br>
        <% end %>
        <!-- sneak in previously filtered min and max values -->
        <% unless @min_max.nil? %>
          <%= hidden_field_tag 'min', @min_max.first %>
          <%= hidden_field_tag 'max', @min_max.last %>
        <% end %>
        <div class="button-container">
        <%= submit_tag("filter", name: nil, class: 'btn btn-primary') %>
      <% end %>

      <!-- button to clear the filter -->
      <%= form_tag({}, {method: :get, enforce_utf8: browser.ie?}) do %>
        <% unless @min_max.nil? %>
          <%= hidden_field_tag 'min', @min_max.first %>
          <%= hidden_field_tag 'max', @min_max.last %>
        <% end %>
        <%= submit_tag("clear", name: nil, class: 'btn btn-primary') %>
      <% end %>
      </div>

    </div>

  </div>
</div>


<!-- price modal -->
<div class="modal fade" id="price" role="dialog">
  <div class="modal-dialog">

    <!-- price content-->
    <div class="modal-content modal-padding modal-background">
      <p class="text-center">The average celestial price is €<%= @ave_price.round  %> </p>
      <%= form_tag({}, {method: :get, enforce_utf8: browser.ie?}) do %>
        <%= render 'shared/slider' %>
        <!-- sneak in previously filtered categories -->
        <% if @categories %>
          <% @categories.each do |category| %>
            <%= hidden_field_tag 'category[]', category %>
          <% end %>
        <% end %>

        <div class="button-container">
        <%= submit_tag("filter", name: nil, class: 'btn btn-primary') %>
      <% end %>

      <!-- button to clear the filter -->
      <%= form_tag({}, {method: :get, enforce_utf8: browser.ie?}) do %>
        <% if @categories %>
          <% @categories.each do |category| %>
            <%= hidden_field_tag 'category[]', category %>
          <% end %>
        <% end %>
        <%= submit_tag("clear", name: nil, class: 'btn btn-primary') %>
      <% end %>

      </div>

    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made to appease our hostile alien overlords.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag 'http://res.cloudinary.com/sensotape/image/upload/v1542991124/ter55nae9yucw8oiwhso.svg', height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Random", celestial_path(Celestial.all.sample), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Explore", celestials_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", conversations_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.avatar, height: 50, width: 50, crop: :thumb, gravity: :face, radius: :max, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <%= t(".profile", default: "My Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t(".settings", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log Out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".log_in", default: "Log In"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Messages</a></li>
        <li><a href="#">Explore</a></li>
        <li><a href="#">Random</a></li>
        <li><a href="#">My Profile</a></li>
        <li><a href="#">Edit Profile</a></li>
        <li><a href="#">Log Out</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_side-card.html.erb
<div class="card side" data-effect="zoom" data-card='<%= index %>'>
  <button class="card__save  js-save" type="button">
    <i class="fa  fa-bookmark"></i>
   </button>
  <figure  class="card__image">
    <%= cl_image_tag celestial.photo, alt: celestial.name %>
  </figure>
  <div class="card__header">
    <figure class="card__profile">

    </figure>
  </div>
  <div class="card__body">
    <h3 class="card__name"><%= celestial.name %></h3>
    <p class="card__job"><%= celestial.category %></p>
    <p class="card__bio"> A really, really cool celestial body.</p>
  </div>
  <div class="card__footer">
    <p class="card__date">Feb 10 2018</p>
    <p class=""></p>
  </div>
</div>

app/views/shared/_slider.html.erb
<div class="range-slider">
  <input name="min" value='<%= @temp_min %>' min='<%= @min_price %>' max='<%= @max_price %>' step="1" type="range"/>
  <input name="max" value='<%= @temp_max %>' min='<%= @min_price %>' max='<%= @max_price %>' step="1" type="range"/>
  <svg width="100%" height="24">
    <line x1="4" y1="0" x2="300" y2="0" stroke="#444" stroke-width="12" stroke-dasharray="1 28"></line>
  </svg>
  <span>
    from
    <input type="number" value='<%= @temp_min %>' min='<%= @min_price %>' max='<%= @max_price %>' style="color: black" />
    to
    <input type="number" value='<%= @temp_max %>' min='<%= @min_price %>' max='<%= @max_price %>' style="color: black" />
  </span>
</div>